In [1]:
from datetime import datetime, timedelta, date
from itertools import cycle
# from lunarcalendar import Converter, Solar, Lunar, DateNotExist
import re
import pandas as pd

In [26]:
preproc = pd.read_excel("data/preproc.xlsx", header=0)

preproc

   Иероглиф   ЗВ часа          Время   甲   乙  丙   丁   戊    己   庚   辛   壬   癸
0         子     Крыса  23.00 - 01.00   甲  丙   戊    庚   壬   甲  丙   戊    庚   壬
1        丑        Бык  01.00 - 03.00   乙  丁    己   辛   癸   乙  丁    己   辛   癸
2         寅      Тигр    3.00 - 5.00  丙   戊    庚   壬   甲  丙   戊    庚   壬   甲
3        卯     Кролик    5.00 - 7.00  丁    己   辛   癸   乙  丁    己   辛   癸   乙
4         辰    Дракон    7.00 - 9.00  戊    庚   壬   甲  丙   戊    庚   壬   甲  丙
5         巳      Змея   9.00 - 11.00   己   辛   癸   乙  丁    己   辛   癸   乙  丁
6         午    Лошадь  11.00 - 13.00   庚   壬   甲  丙   戊    庚   壬   甲  丙   戊
7        未       Коза  13.00 - 15.00   辛   癸   乙  丁    己   辛   癸   乙  丁    己
8        申   Обезьяна  15.00 - 17.00   壬   甲  丙   戊    庚   壬   甲  丙   戊    庚
9         酉     Петух  17.00 - 19.00   癸   乙  丁    己   辛   癸   乙  丁    己   辛
10       戌     Собака  19.00 - 21.00   甲  丙   戊    庚   壬   甲  丙   戊    庚   壬
11        亥    Свинья  21.00 - 23.00   乙  丁    己   辛   癸   乙  丁    己   辛   癸

In [27]:
preproc['Время'] = preproc['Время'].astype("str").str.replace('.', ':')

In [28]:
preproc.dropna(axis=1, inplace=True)

for c in preproc.columns:
    preproc[c] = preproc[c].str.strip()

In [40]:
s = '23:00 - 01:00'
re.search(r"(\d*)", s)[0]

'23'

In [57]:
preproc['Время_int'] = preproc['Время_int'].astype('str')
for s in preproc['Время_int']:
    s = re.search(r"(\d*)", s)[0]

In [63]:
preproc['Время_int'] = preproc['Время_int'].str.extract(r'(\d*)', expand=False).str.lstrip("0")

In [64]:
preproc

   Иероглиф   ЗВ часа          Время  甲  乙  丙  丁  戊  己  庚  辛  壬  癸 Время_int
0         子     Крыса  23:00 - 01:00  甲  丙  戊  庚  壬  甲  丙  戊  庚  壬        23
1         丑       Бык  01:00 - 03:00  乙  丁  己  辛  癸  乙  丁  己  辛  癸         1
2         寅      Тигр    3:00 - 5:00  丙  戊  庚  壬  甲  丙  戊  庚  壬  甲         3
3         卯    Кролик    5:00 - 7:00  丁  己  辛  癸  乙  丁  己  辛  癸  乙         5
4         辰    Дракон    7:00 - 9:00  戊  庚  壬  甲  丙  戊  庚  壬  甲  丙         7
5         巳      Змея   9:00 - 11:00  己  辛  癸  乙  丁  己  辛  癸  乙  丁         9
6         午    Лошадь  11:00 - 13:00  庚  壬  甲  丙  戊  庚  壬  甲  丙  戊        11
7         未      Коза  13:00 - 15:00  辛  癸  乙  丁  己  辛  癸  乙  丁  己        13
8         申  Обезьяна  15:00 - 17:00  壬  甲  丙  戊  庚  壬  甲  丙  戊  庚        15
9         酉     Петух  17:00 - 19:00  癸  乙  丁  己  辛  癸  乙  丁  己  辛        17
10        戌    Собака  19:00 - 21:00  甲  丙  戊  庚  壬  甲  丙  戊  庚  壬        19
11        亥    Свинья  21:00 - 23:00  乙  丁  己  辛  癸  乙  丁  己  辛  癸        21

In [65]:
preproc.to_csv("data/feitenbafa.csv", index=False)